name: CicdProblem

on: [push]

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v2
   - name: print code
     run: python hello.py
 build:
  runs-on: ubuntu-latest
  needs: [test]
  steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: create artifact
      uses: actions/upload-artifact@v4
      with: 
        name: hello
        path: .
