name: pipeline

on: [push]
env:
 APPLICATION_NAME: APP2
jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
    - name: checkout Code
      uses: actions/checkout@v2
    - name: Setup python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name:  Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py 
    - name:  Run unit tests
      run: |
        python -m unittest --verbose --failfast


