name: pipeline

on: [push]
env:
 APPLICATION_NAME: APP2
jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
    - name: checkout Code
      uses: actions/checkout@v2
    - name: Setup python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name:  Lint code
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name:  Run unit tests
      run: |
        python -m unittest --verbose --failfast


